#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Section 6 of RESULT.md: what governs the size of S(f), and the hypothesis
that failed.

    python src/counting.py        # writes data/counting.txt (minutes, not seconds)

Phi_3 and Phi_6 have essentially the same covered set and wildly different
|S(f)|, which suggested that the ARROW density is what governs the size. Those
two therefore cannot test it; the other eight functions here are out of sample.

`verify.py` recomputes the two densities live (they are cheap) and recomputes
the rank correlation from this table, so the only thing taken from disk is the
|S(f)| column -- and that is regenerated by this one command.
"""
from __future__ import annotations

import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from excluded import (S_of_f, digraph, has_root,   # noqa: E402
                      sieve, smallest_prime_factors)

random.seed(20260906)
DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "data")

N = 400000
PRIME_BOUND = 800

FUNCTIONS = [
    # name, F, f(q,e), formed-the-hypothesis?
    ("Phi_3", [1, 1, 1], lambda q, e: q ** (2 * e) + q ** e + 1, True),
    ("Phi_6", [1, -1, 1], lambda q, e: q ** (2 * e) - q ** e + 1, True),
    ("x+1", [1, 1], lambda q, e: q ** e + 1, False),
    ("x-1", [1, -1], lambda q, e: q ** e - 1, False),
    ("x^2+1", [1, 0, 1], lambda q, e: q ** (2 * e) + 1, False),
    ("Phi_5", [1, 1, 1, 1, 1],
     lambda q, e: sum(q ** (i * e) for i in range(5)), False),
    ("Phi_8", [1, 0, 0, 0, 1], lambda q, e: q ** (4 * e) + 1, False),
    ("x^3-x-1", [1, 0, -1, -1], lambda q, e: q ** (3 * e) - q ** e - 1, False),
    ("x^3+x^2-2x-1", [1, 1, -2, -1],
     lambda q, e: q ** (3 * e) + q ** (2 * e) - 2 * q ** e - 1, False),
    ("x^4-x-1", [1, 0, 0, -1, -1], lambda q, e: q ** (4 * e) - q ** e - 1, False),
]


def densities(F):
    """(excluded density, arrow density) over the primes below PRIME_BOUND."""
    primes = sieve(PRIME_BOUND)
    covered = [p for p in primes if has_root(F, p)]
    excluded = 1 - len(covered) / len(primes)
    adj, _ = digraph(F, covered)
    pairs = len(covered) * (len(covered) - 1)
    arrows = sum(len(v) for v in adj.values()) / pairs if pairs else 0.0
    return excluded, arrows


def spearman(xs, ys):
    def ranks(v):
        order = sorted(range(len(v)), key=lambda i: v[i])
        r = [0.0] * len(v)
        i = 0
        while i < len(order):
            j = i
            while j + 1 < len(order) and v[order[j + 1]] == v[order[i]]:
                j += 1
            mid = (i + j) / 2 + 1
            for k in range(i, j + 1):
                r[order[k]] = mid
            i = j + 1
        return r
    a, b = ranks(xs), ranks(ys)
    n = len(a)
    ma, mb = sum(a) / n, sum(b) / n
    num = sum((x - ma) * (y - mb) for x, y in zip(a, b))
    den = (sum((x - ma) ** 2 for x in a) * sum((y - mb) ** 2 for y in b)) ** 0.5
    return num / den if den else 0.0


def main():
    os.makedirs(DATA, exist_ok=True)
    spf = smallest_prime_factors(N)
    rows = ["# Section 6 of RESULT.md.  |S(f)| counts n = 1, and is computed as",
            "# plain integers up to %d.  Densities over the %d primes below %d."
            % (N, len(sieve(PRIME_BOUND)), PRIME_BOUND),
            "# name\texcluded density\tarrow density\t|S(f)|\tformed the hypothesis?"]
    xs_arrow, xs_excl, ys = [], [], []
    for name, F, f, formed in FUNCTIONS:
        excl, arr = densities(F)
        size = len(S_of_f(f, N, spf)) - 1
        rows.append("%s\t%.4f\t%.4f\t%d\t%s"
                    % (name, excl, arr, size, "yes" if formed else "no"))
        if not formed:
            xs_arrow.append(arr)
            xs_excl.append(excl)
            ys.append(size)
        print("  %-14s excluded %.4f  arrows %.4f  |S(f)| %d%s"
              % (name, excl, arr, size, "   (formed H)" if formed else ""))
    rows.append("# out of sample, %d functions:" % len(ys))
    rows.append("# spearman(|S(f)|, arrow density)\t%+.3f"
                % spearman(xs_arrow, ys))
    rows.append("# spearman(|S(f)|, excluded density)\t%+.3f"
                % spearman(xs_excl, ys))
    rows.append("# 5%% critical value of Spearman at n = %d is 0.738" % len(ys))
    path = os.path.join(DATA, "counting.txt")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(rows) + "\n")
    print("wrote data/counting.txt")


if __name__ == "__main__":
    main()
